server:
  port: 8080

chicken:
  rollen:
    organisator: ilumary, dniklas27
    tutor: ilumary, causebencancode, dniklas27

  startdatum: ${STARTDATUM:}
  enddatum: ${ENDDATUM:}

spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:mariadb://localhost:3322/
    user: root
    password: iamgroot

  datasource:
    username: root
    password: iamgroot
    url: jdbc:mariadb://localhost:3322/chicken

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user, id

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token

logging:
  level:
    root: debug